### ISSUE TITLE
Laravel Spark / Cashier Paddle slowing down PestPHP tests tremendously.

### ISSUE THREAD

**Issue by DanjBethel** [laravel/cashier-paddle#267]
### Cashier Paddle Version

2.5.0

### Laravel Version

11.15.0

### PHP Version

8.3

### Description

I assume that the "createAsCustomer" booted method in the Billable class is being ran every time I refresh and seed my database and also when I am running my test. Without the "Billable" trait my test run in 6 seconds. With the trait it takes 45 seconds. Am I able to disable this when testing? Any suggestions are welcome

### Steps To Reproduce

Just run test using PestPHP with the "Billable" trait versus without. My application is multi-tenant, so most of my tests require me to create the Billable model in order to attach it to another model.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
There's unfortunately no way around this right now. You could potentially mock the underlying HTTP calls to paddle using https://laravel.com/docs/11.x/http-client#faking-responses
