### ISSUE TITLE
CustomerUpdated Class throwing errors on webhooks.

### ISSUE THREAD

**Issue by emergingdzns** [laravel/cashier-paddle#279]
### Cashier Paddle Version

2.5.1

### Laravel Version

11.2

### PHP Version

8.3

### Database Driver & Version

Amazon RDS

### Description

When the customer.updated webhook is received by the Paddle webhook, it is throwing this error:
```
Laravel\Paddle\Events\CustomerUpdated::__construct(): Argument #1 ($billable) must be of type Illuminate\Database\Eloquent\Model, null given, called in /var/www/server/web-app/vendor/laravel/framework/src/Illuminate/Foundation/Events/Dispatchable.php on line 14
```

This class is untouched by us and we don't have any listeners setup on this event either.

### Steps To Reproduce

Setup laravel with paddle and cashier.
Subscribe to the customer.updated webhook notification on Paddle.
Receive the webhook upon updating a customer.

**Comment by driesvints** [comment]
I sincerely doubt this is an actual bug since we would have gotten this a lot sooner and more frequent. Please try asking on a support channel first:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
