### ISSUE TITLE
1 Month subscription save the ends_at date - 3 months subscription ends_at missing

### ISSUE THREAD

**Issue by FreddyCrugger** [laravel/cashier-paddle#82]
- Cashier Paddle Version: 1.2.0
- Laravel Version: 8.6.0
- PHP Version: 7.3
- Database Driver & Version: libmysql - 5.6.43

### Description:
When a subscription is created in Paddle with a billing interval of 1 month, the ends_at column is filled with the right date.
When a subscription is created in Paddle with a billing interval of 3 months, the ends_at column shows as NULL.

Paddle example of a 3 months subscription.

### Steps To Reproduce:
Create in Paddle:
A 1-month SUBSCRIPTION billing interval.
A 3-months SUBSCRIPTION billing interval.

When a subscription is created in Paddle with a billing interval of 1 month, the ends_at column is filled with the right date.
When a subscription is created in Paddle with a billing interval of 3 months, the ends_at column shows as NULL.

**Comment by driesvints** [comment]
The ends_at is only filled in when a subscription is cancelled or when it still needs to fulfil some trial days. Please post the exact setup of your subscriptions and the source code to reproduce this.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by VincentNdegwa** [comment]
## Issue Description

I am encountering the following issue with Laravel Cashier Paddle. When creating a new subscription, the subscription is created successfully, but the `ends_at` column is set to `null`. I believe this column should contain a timestamp indicating when the subscription is supposed to end.

### Environment

- **Laravel Version**: 11
- **Laravel Cashier Paddle Version**: 2.5
- **PHP Version**: 8.2
- **Database**: MySQL 10.6.19-MariaDB
- **Operating System**: Ubuntu 22.04

### Steps to Reproduce

1. Logged into the Paddle dashboard.
2. Opened the "Products" section from the catalog sidebar.
3. Created a new product named "Basic" to represent the basic subscription plan.
4. Viewed the newly created product.
5. Created a new price (billing monthly).

   ![image](https://github.com/user-attachments/assets/7e3b49d5-24ee-4c13-a69a-a91abcd04396)

6. After creating the price, copied the `priceId` provided in the interface and used it to create the subscription.

   ![image](https://github.com/user-attachments/assets/510ef60e-f94d-4141-a0c3-3d4a7c00f7cf)

### Expected Behavior

The `ends_at` column should contain a valid timestamp indicating when the subscription will end.

### Actual Behavior

The `ends_at` column is `null` after the subscription is created.

   ![image](https://github.com/user-attachments/assets/f76ab9db-ac53-4ed2-8380-769357ec2d99)
